services:
  - name: api-service
    type: web
    env: go
    plan: free
    buildCommand: go build -o api ./cmd/api
    startCommand: ./api
    envVars:
      - name: API_URL
        value: "https://api-service-ub0y.onrender.com"

  - name: aiservice-service
    type: web
    env: go
    plan: free
    buildCommand: go build -o aiservice ./cmd/aiservice
    startCommand: ./aiservice
    envVars:
      - name: AI_URL
        value: "https://aiservice-service.onrender.com"

  - name: frontend
    type: web
    env: node
    plan: free
    buildCommand: cd webs && npm install && npm run build
    startCommand: cd webs && npm install -g serve && serve -s dist
    envVars:
      - name: VITE_API_URL
        value: "https://api-service-ub0y.onrender.com"
      - name: VITE_AI_URL
        value: "https://aiservice-service.onrender.com"
